require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WpPostmetaController do

  # This should return the minimal set of attributes required to create a valid
  # WpPostmetum. As you add validations to WpPostmetum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "meta_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WpPostmetaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wp_postmeta as @wp_postmeta" do
      wp_postmetum = WpPostmetum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wp_postmeta).should eq([wp_postmetum])
    end
  end

  describe "GET show" do
    it "assigns the requested wp_postmetum as @wp_postmetum" do
      wp_postmetum = WpPostmetum.create! valid_attributes
      get :show, {:id => wp_postmetum.to_param}, valid_session
      assigns(:wp_postmetum).should eq(wp_postmetum)
    end
  end

  describe "GET new" do
    it "assigns a new wp_postmetum as @wp_postmetum" do
      get :new, {}, valid_session
      assigns(:wp_postmetum).should be_a_new(WpPostmetum)
    end
  end

  describe "GET edit" do
    it "assigns the requested wp_postmetum as @wp_postmetum" do
      wp_postmetum = WpPostmetum.create! valid_attributes
      get :edit, {:id => wp_postmetum.to_param}, valid_session
      assigns(:wp_postmetum).should eq(wp_postmetum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WpPostmetum" do
        expect {
          post :create, {:wp_postmetum => valid_attributes}, valid_session
        }.to change(WpPostmetum, :count).by(1)
      end

      it "assigns a newly created wp_postmetum as @wp_postmetum" do
        post :create, {:wp_postmetum => valid_attributes}, valid_session
        assigns(:wp_postmetum).should be_a(WpPostmetum)
        assigns(:wp_postmetum).should be_persisted
      end

      it "redirects to the created wp_postmetum" do
        post :create, {:wp_postmetum => valid_attributes}, valid_session
        response.should redirect_to(WpPostmetum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wp_postmetum as @wp_postmetum" do
        # Trigger the behavior that occurs when invalid params are submitted
        WpPostmetum.any_instance.stub(:save).and_return(false)
        post :create, {:wp_postmetum => { "meta_id" => "invalid value" }}, valid_session
        assigns(:wp_postmetum).should be_a_new(WpPostmetum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WpPostmetum.any_instance.stub(:save).and_return(false)
        post :create, {:wp_postmetum => { "meta_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wp_postmetum" do
        wp_postmetum = WpPostmetum.create! valid_attributes
        # Assuming there are no other wp_postmeta in the database, this
        # specifies that the WpPostmetum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WpPostmetum.any_instance.should_receive(:update_attributes).with({ "meta_id" => "1" })
        put :update, {:id => wp_postmetum.to_param, :wp_postmetum => { "meta_id" => "1" }}, valid_session
      end

      it "assigns the requested wp_postmetum as @wp_postmetum" do
        wp_postmetum = WpPostmetum.create! valid_attributes
        put :update, {:id => wp_postmetum.to_param, :wp_postmetum => valid_attributes}, valid_session
        assigns(:wp_postmetum).should eq(wp_postmetum)
      end

      it "redirects to the wp_postmetum" do
        wp_postmetum = WpPostmetum.create! valid_attributes
        put :update, {:id => wp_postmetum.to_param, :wp_postmetum => valid_attributes}, valid_session
        response.should redirect_to(wp_postmetum)
      end
    end

    describe "with invalid params" do
      it "assigns the wp_postmetum as @wp_postmetum" do
        wp_postmetum = WpPostmetum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WpPostmetum.any_instance.stub(:save).and_return(false)
        put :update, {:id => wp_postmetum.to_param, :wp_postmetum => { "meta_id" => "invalid value" }}, valid_session
        assigns(:wp_postmetum).should eq(wp_postmetum)
      end

      it "re-renders the 'edit' template" do
        wp_postmetum = WpPostmetum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WpPostmetum.any_instance.stub(:save).and_return(false)
        put :update, {:id => wp_postmetum.to_param, :wp_postmetum => { "meta_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wp_postmetum" do
      wp_postmetum = WpPostmetum.create! valid_attributes
      expect {
        delete :destroy, {:id => wp_postmetum.to_param}, valid_session
      }.to change(WpPostmetum, :count).by(-1)
    end

    it "redirects to the wp_postmeta list" do
      wp_postmetum = WpPostmetum.create! valid_attributes
      delete :destroy, {:id => wp_postmetum.to_param}, valid_session
      response.should redirect_to(wp_postmeta_url)
    end
  end

end
