require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WpUsersController do

  # This should return the minimal set of attributes required to create a valid
  # WpUser. As you add validations to WpUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "ID" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WpUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wp_users as @wp_users" do
      wp_user = WpUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wp_users).should eq([wp_user])
    end
  end

  describe "GET show" do
    it "assigns the requested wp_user as @wp_user" do
      wp_user = WpUser.create! valid_attributes
      get :show, {:id => wp_user.to_param}, valid_session
      assigns(:wp_user).should eq(wp_user)
    end
  end

  describe "GET new" do
    it "assigns a new wp_user as @wp_user" do
      get :new, {}, valid_session
      assigns(:wp_user).should be_a_new(WpUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested wp_user as @wp_user" do
      wp_user = WpUser.create! valid_attributes
      get :edit, {:id => wp_user.to_param}, valid_session
      assigns(:wp_user).should eq(wp_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WpUser" do
        expect {
          post :create, {:wp_user => valid_attributes}, valid_session
        }.to change(WpUser, :count).by(1)
      end

      it "assigns a newly created wp_user as @wp_user" do
        post :create, {:wp_user => valid_attributes}, valid_session
        assigns(:wp_user).should be_a(WpUser)
        assigns(:wp_user).should be_persisted
      end

      it "redirects to the created wp_user" do
        post :create, {:wp_user => valid_attributes}, valid_session
        response.should redirect_to(WpUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wp_user as @wp_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        WpUser.any_instance.stub(:save).and_return(false)
        post :create, {:wp_user => { "ID" => "invalid value" }}, valid_session
        assigns(:wp_user).should be_a_new(WpUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WpUser.any_instance.stub(:save).and_return(false)
        post :create, {:wp_user => { "ID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wp_user" do
        wp_user = WpUser.create! valid_attributes
        # Assuming there are no other wp_users in the database, this
        # specifies that the WpUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WpUser.any_instance.should_receive(:update_attributes).with({ "ID" => "1" })
        put :update, {:id => wp_user.to_param, :wp_user => { "ID" => "1" }}, valid_session
      end

      it "assigns the requested wp_user as @wp_user" do
        wp_user = WpUser.create! valid_attributes
        put :update, {:id => wp_user.to_param, :wp_user => valid_attributes}, valid_session
        assigns(:wp_user).should eq(wp_user)
      end

      it "redirects to the wp_user" do
        wp_user = WpUser.create! valid_attributes
        put :update, {:id => wp_user.to_param, :wp_user => valid_attributes}, valid_session
        response.should redirect_to(wp_user)
      end
    end

    describe "with invalid params" do
      it "assigns the wp_user as @wp_user" do
        wp_user = WpUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WpUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => wp_user.to_param, :wp_user => { "ID" => "invalid value" }}, valid_session
        assigns(:wp_user).should eq(wp_user)
      end

      it "re-renders the 'edit' template" do
        wp_user = WpUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WpUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => wp_user.to_param, :wp_user => { "ID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wp_user" do
      wp_user = WpUser.create! valid_attributes
      expect {
        delete :destroy, {:id => wp_user.to_param}, valid_session
      }.to change(WpUser, :count).by(-1)
    end

    it "redirects to the wp_users list" do
      wp_user = WpUser.create! valid_attributes
      delete :destroy, {:id => wp_user.to_param}, valid_session
      response.should redirect_to(wp_users_url)
    end
  end

end
